core/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path('create', views.ChatroomCreateView.as_view(), name='create-chatroom'),
    path('<str:room_name>', views.ChatroomGroupChatView.as_view(), name='group-chat-room'),
]

core/core/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chatroom/', include('chat.urls')),
    path("",RedirectView.as_view(url="/chatroom/create"))
]

core/chat/models.py
from django.db import models

# Create your models here.

core/chat/forms.py
from django import forms

class ChatCreateForm(forms.Form):
    chat_room_name = forms.CharField(required=True)
    display_name = forms.CharField(required=True)

core/chat/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import *

class ChatroomCreateView(FormView):
    template_name = "chat/chatroom-create.html"
    form_class = ChatCreateForm
    
    def form_valid(self, form):
        chat_room_name = form.cleaned_data.get("chat_room_name")
        display_name = form.cleaned_data.get("display_name")
        self.request.session.update({"display_name":display_name})
        return HttpResponseRedirect(reverse_lazy("chat:group-chat-room",kwargs={"room_name":chat_room_name}))
    
    
    def form_invalid(self, form):
        return super().form_invalid(form)
        
    
    
class ChatroomGroupChatView(TemplateView):
    template_name = "chat/chatroom-group-chat.html"
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["room_name"] = kwargs.get("room_name")
        context["display_name"] = self.request.session.get("display_name","Undefined User")
        return context

core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Server</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra_css %}
    {% endblock extra_css %}
</head>

<body>

    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% block extra_js %}
    {% endblock extra_js %}
</body>

</html>

core/templates/chat/chatroom-create.html
{% extends 'base.html' %}

{% block extra_css %}
<style>

    .login-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }
      .login-form {
        width: 100%;
        max-width: 400px;
        padding: 15px;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f8f9fa;
      }
</style>
{% endblock extra_css %}

{% block content %}

<div class="login-container">
    <form action="{% url 'chat:create-chatroom' %}" method="post" class="login-form">
      {% csrf_token %}
      <h2 class="text-center mb-4">Join Chat Room</h2>
      <div class="mb-3">
        <label for="chatRoomName" class="form-label">Chat Room Name</label>
        <input type="text" class="form-control" name="chat_room_name" placeholder="Enter chat room name" required>
      </div>
      <div class="mb-3">
        <label for="displayName" class="form-label">Display Name</label>
        <input type="text" class="form-control"  name="display_name" placeholder="Enter your display name" required>
      </div>
      <div class="d-grid">
        <button type="submit" class="btn btn-primary">Join Chat</button>
      </div>
    </form>
  </div>

{% endblock %}

core/templates/chat/chatroom-group-chat.html
{% extends 'base.html' %}

{% block extra_css %}
<style>
    .chat-container {
        display: flex;
        flex-direction: column;
        height: 100vh;
        padding-top: 100px;
        padding-bottom: 100px;
    }

    .chat-messages {
        flex: 1;
        overflow-y: auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        margin-bottom: 10px;
        background-color: #f8f9fa;
    }

    .chat-message {
        margin-bottom: 10px;
    }

    .chat-message .display-name {
        font-weight: bold;
        margin-right: 5px;
    }

    .chat-box {
        display: flex;
    }

    .chat-box input {
        flex: 1;
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }

    .chat-box button {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }
</style>
{% endblock extra_css %}


{% block content %}
<div class="container chat-container">
    <div class="chat-messages" id="chatMessages">
        <!-- Chat messages will appear here -->
    </div>
    <div class="chat-box">
        <input type="text" class="form-control" id="chat-message-input" placeholder="Type your message...">
        <button class="btn btn-primary" id="chat-message-submit">Send</button>
    </div>
</div>

<div id="room-name" style="display: none;">{{ room_name }}</div>
{% endblock %}

{% block extra_js %}
<script>
    console.log(window.location.host)
    const roomName = document.getElementById('room-name').textContent
    const protocol = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
    const chatSocket = new WebSocket(
        protocol
        + window.location.host
        + '/ws/chat/'
        + roomName
    );
    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        const chatMessages = document.getElementById('chatMessages');
        const messageElement = document.createElement('div');
        messageElement.className = 'chat-message';
        messageElement.innerHTML = `<span class="display-name">${data.display_name}:</span> <span class="message">${data.message}</span>`;
        chatMessages.appendChild(messageElement);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.getElementById('chat-message-input').focus();
    document.getElementById('chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.getElementById('chat-message-submit').click();
        }
    };

    document.getElementById('chat-message-submit').onclick = function (e) {
        const messageInputDom = document.getElementById('chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'display_name': `{{display_name}}`  // Replace with dynamic username
        }));
        messageInputDom.value = '';
    };
</script>

{% endblock extra_js %}